version: '3'
services:

  orchestrator_0:
    image: jmorin98/orchestrator
    hostname: orchestrator_0
    environment:
      NODE_ID: orchestrator_0
      IP: '127.0.0.1'
      PUBLIC_PORT: 5001
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      ALGORITHM: TC
      PRESENTATION: 0
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5001:5000
    
  node_2:
    image: jmorin98/orchestrator
    hostname: node_2
    environment:
      NODE_ID: node_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5002
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: orchestrator_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5001
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5002:5000
  
  node_3:
    image: jmorin98/orchestrator
    hostname: node_3
    environment:
      NODE_ID: node_3
      IP: '127.0.0.1'
      PUBLIC_PORT: 5003
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: orchestrator_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5001
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5003:5000

networks:
  workers_v3: