version: '3'
services:

  espatial_0:
    image: jmorin98/orchestrator
    hostname: espatial_0
    environment:
      NODE_ID: espatial_0
      IP: '127.0.0.1'
      PUBLIC_PORT: 5001
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      ALGORITHM: RR
      PRESENTATION: 0

    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5001:5000
    
  temporal_1:
    image: jmorin98/orchestrator
    hostname: temporal_1
    environment:
      NODE_ID: temporal_1
      IP: '127.0.0.1'
      PUBLIC_PORT: 5002
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1
      ALGORITHM: TC

      NODE_ID_MANAGER: espatial_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5001
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5002:5000
  
  temporal_2:
    image: jmorin98/orchestrator
    hostname: temporal_2
    environment:
      NODE_ID: temporal_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5003
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1
      ALGORITHM: TC

      NODE_ID_MANAGER: espatial_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5001
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5003:5000

  fusion_1:
    image: jmorin98/fusion
    hostname: fusion_1
    environment:
      NODE_ID: fusion_1
      IP: '127.0.0.1'
      PUBLIC_PORT: 5004
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: temporal_1
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5002
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5004:5000

  fusion_2:
    image: jmorin98/fusion
    hostname: fusion_2
    environment:
      NODE_ID: fusion_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5005
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: temporal_1
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5002
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5005:5000
  
  fusion_3:
    image: jmorin98/fusion
    hostname: fusion_3
    environment:
      NODE_ID: fusion_3
      IP: '127.0.0.1'
      PUBLIC_PORT: 5006
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: temporal_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5003
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5006:5000
  
  fusion_4:
    image: jmorin98/fusion
    hostname: fusion_4
    environment:
      NODE_ID: fusion_4
      IP: '127.0.0.1'
      PUBLIC_PORT: 5007
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: temporal_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5003
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5007:5000
    
  mediaClass_1:
    image: jmorin98/media
    hostname: mediaClass_1
    environment:
      NODE_ID: mediaClass_1
      IP: '127.0.0.1'
      PUBLIC_PORT: 5008
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: fusion_1
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5004
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5008:5000

  mediaClass_2:
    image: jmorin98/media
    hostname: mediaClass_2
    environment:
      NODE_ID: mediaClass_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5009
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: fusion_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5005
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5009:5000
  
  mediaClass_3:
    image: jmorin98/media
    hostname: mediaClass_3
    environment:
      NODE_ID: mediaClass_3
      IP: '127.0.0.1'
      PUBLIC_PORT: 5010
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: fusion_3
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5006
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5010:5000
  
  mediaClass_4:
    image: jmorin98/media
    hostname: mediaClass_4
    environment:
      NODE_ID: mediaClass_4
      IP: '127.0.0.1'
      PUBLIC_PORT: 5011
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 1
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: fusion_4
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5007
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5011:5000

  correlation_1:
    image: jmorin98/correlation
    hostname: correlation_1
    environment:
      NODE_ID: correlation_1
      IP: '127.0.0.1'
      PUBLIC_PORT: 5012
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: mediaClass_1
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5008
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5012:5000

  correlation_2:
    image: jmorin98/correlation
    hostname: correlation_2
    environment:
      NODE_ID: correlation_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5013
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: mediaClass_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5009
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5013:5000
  
  correlation_3:
    image: jmorin98/correlation
    hostname: correlation_3
    environment:
      NODE_ID: correlation_3
      IP: '127.0.0.1'
      PUBLIC_PORT: 5014
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: mediaClass_3
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5010
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5014:5000
  
  correlation_4:
    image: jmorin98/correlation
    hostname: correlation_4
    environment:
      NODE_ID: correlation_4
      IP: '127.0.0.1'
      PUBLIC_PORT: 5015
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
      PRESENTATION: 1

      NODE_ID_MANAGER: mediaClass_4
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5011
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /test/prototipoTest/:/app/data/
      - /test/prototipoTest/logs/:/app/data/logs
    networks:
      - workers_v3
    ports:
      - 5015:5000

networks:
  workers_v3: